project_id = "jiqbgxtgzpdosbmydfcw"

[functions.send-whatsapp]
verify_jwt = false

[functions.test-whatsapp]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.test-sms]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.sales-chat]
verify_jwt = false

[functions.create-member]
verify_jwt = false

[functions.send-referral]
verify_jwt = false
